# TODO: can simplify db setup once have docker images created on hub
services:
  badapple_db:
    restart: always
    build:
      context: https://github.com/unmtransinfo/Badapple2.git#main
      dockerfile: Dockerfile
      args:
        - DB_PORT=${DB_PORT}
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - PGDUMP_URL=${DB_PGDUMP_URL}
        - TZ=${TZ}
    container_name: badapple_classic_db
    ports:
      - "127.0.0.1:${DB_PORT}:${DB_PORT}"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - PGDUMP_URL=${DB_PGDUMP_URL}
      - TZ=${TZ}
    env_file:
      - local.env
    volumes:
      - badapple_classic_data:/var/lib/postgresql/14/main
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -p ${DB_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - badapple_network

  badapple2_db:
    restart: always
    build:
      context: https://github.com/unmtransinfo/Badapple2.git#main
      dockerfile: Dockerfile
      args:
        - DB_PORT=${DB2_PORT}
        - DB_NAME=${DB2_NAME}
        - DB_USER=${DB2_USER}
        - DB_PASSWORD=${DB2_PASSWORD}
        - PGDUMP_URL=${DB2_PGDUMP_URL}
        - TZ=${TZ}
    container_name: badapple2_db
    ports:
      - "127.0.0.1:${DB2_PORT}:${DB2_PORT}"
    environment:
      - DB_NAME=${DB2_NAME}
      - DB_USER=${DB2_USER}
      - DB_PASSWORD=${DB2_PASSWORD}
      - DB_PORT=${DB2_PORT}
      - PGDUMP_URL=${DB2_PGDUMP_URL}
      - TZ=${TZ}
    env_file:
      - local.env
    volumes:
      - badapple2_data:/var/lib/postgresql/14/main
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB2_NAME} -p ${DB2_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - badapple_network

  badapple_api:
    restart: always
    build:
      context: ./app
    ports:
      - "127.0.0.1:${APP_PORT}:${APP_PORT}"
    environment:
      - APP_PORT=${APP_PORT}
      - DB_HOST=badapple_db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB2_HOST=badapple2_db
      - DB2_NAME=${DB2_NAME}
      - DB2_USER=${DB2_USER}
      - DB2_PASSWORD=${DB2_PASSWORD}
      - DB2_PORT=${DB2_PORT}
    env_file:
      - local.env
    depends_on:
      badapple_db:
        condition: service_healthy
      badapple2_db:
        condition: service_healthy
    networks:
      - badapple_network

  badapple_ui:
    restart: always
    build:
      context: https://github.com/unmtransinfo/Badapple2-UI.git#main
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    env_file:
      - local.env
    ports:
      - "127.0.0.1:${UI_PORT}:8080"
    command: npx vite --port 8080
    networks:
      - badapple_network

volumes:
  badapple_classic_data:
  badapple2_data:

networks:
  badapple_network:
