services:
  badapple_db:
    restart: always
    build:
      context: https://github.com/unmtransinfo/Badapple2.git#main
      dockerfile: Dockerfile
      args:
        - DB_PORT=${DB_PORT}
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - PGDUMP_URL=${DB_PGDUMP_URL}
        - TZ=${TZ}
    container_name: badapple_classic_db
    ports:
      - "127.0.0.1:${DB_PORT}:${DB_PORT}" # 127.0.0.1 to restrict to localhost
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - PGDUMP_URL=${DB_PGDUMP_URL}
      - TZ=${TZ}
    env_file:
      - .env
    volumes:
      - badapple_classic_data:/var/lib/postgresql/14/main
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -p ${DB_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - badapple_backend
  
  badapple2_db:
    restart: always
    build:
      context: https://github.com/unmtransinfo/Badapple2.git#main
      dockerfile: Dockerfile
      args:
        - DB_PORT=${DB2_PORT}
        - DB_NAME=${DB2_NAME}
        - DB_USER=${DB2_USER}
        - DB_PASSWORD=${DB2_PASSWORD}
        - PGDUMP_URL=${DB2_PGDUMP_URL}
        - TZ=${TZ}
    container_name: badapple2_db
    ports:
      - "127.0.0.1:${DB2_PORT}:${DB2_PORT}" # 127.0.0.1 to restrict to localhost
    environment:
      - DB_NAME=${DB2_NAME}
      - DB_USER=${DB2_USER}
      - DB_PASSWORD=${DB2_PASSWORD}
      - DB_PORT=${DB2_PORT}
      - PGDUMP_URL=${DB2_PGDUMP_URL}
      - TZ=${TZ}
    env_file:
      - .env
    volumes:
      - badapple2_data:/var/lib/postgresql/14/main
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB2_NAME} -p ${DB2_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - badapple_backend

  badapple_api:
    restart: always
    build:
      context: ./app
    environment:
      - APP_PORT=${APP_PORT}
      - DB_HOST=badapple_db # host is docker service
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB2_HOST=badapple2_db
      - DB2_NAME=${DB2_NAME}
      - DB2_USER=${DB2_USER}
      - DB2_PASSWORD=${DB2_PASSWORD}
      - DB2_PORT=${DB2_PORT}
    env_file:
      - .env
    depends_on:
      badapple_db:
        condition: service_healthy
      badapple2_db:
        condition: service_healthy
    volumes:
      - static_files_flasgger:/app/flasgger_static/
    networks:
      - badapple_backend
      - badapple_frontend

  badapple_ui:
    build:
      context: https://github.com/unmtransinfo/Badapple2-UI.git#context_dec_11
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    env_file:
      - .env
    command: npx vite build
    volumes:
      - static_files_badapple:/app/dist/
    networks:
      - badapple_frontend

  badapple_nginx:
    restart: always
    image: nginx:1
    volumes:
      - static_files_badapple:/usr/share/nginx/html/static_files_badapple:ro
      - static_files_flasgger:/usr/share/nginx/html/static_files_flasgger:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx:/etc/nginx
    ports:
      - "${BADAPPLE_NGINX_SSL_PORT:-443}:443"
      - "${BADAPPLE_NGINX_HTTP_PORT:-80}:80"
    depends_on:
      badapple_api:
        condition: service_started
      badapple_ui:
        condition: service_completed_successfully
    networks:
      - badapple_frontend

volumes:
  badapple_classic_data:
  badapple2_data:
  static_files_badapple:
  static_files_flasgger:
  nginx:

networks:
  badapple_frontend:
  badapple_backend: