# TODO: can simplify db setup once have docker images created on hub
name: badapple2-local
services:
  db:
    build:
      context: https://github.com/unmtransinfo/Badapple2.git#main
      dockerfile: Dockerfile
      args:
        - DB_PORT=${DB_PORT}
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - PGDUMP_URL=${DB_PGDUMP_URL}
        - TZ=${TZ}
    container_name: badapple_classic_db
    volumes:
      - badapple_classic_data:/var/lib/postgresql/14/main
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - PGDUMP_URL=${DB_PGDUMP_URL}
      - TZ=${TZ}
    env_file:
      - local.env
    ports:
      # exposing DB ports here for easier DB-access from localhost
      - "127.0.0.1:${DB_PORT}:${DB_PORT}"
    networks:
      - badapple_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${DB_NAME} -p ${DB_PORT}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db2:
    build:
      context: https://github.com/unmtransinfo/Badapple2.git#main
      dockerfile: Dockerfile
      args:
        - DB_PORT=${DB2_PORT}
        - DB_NAME=${DB2_NAME}
        - DB_USER=${DB2_USER}
        - DB_PASSWORD=${DB2_PASSWORD}
        - PGDUMP_URL=${DB2_PGDUMP_URL}
        - TZ=${TZ}
    container_name: db2
    volumes:
      - badapple2_data:/var/lib/postgresql/14/main
    environment:
      - DB_NAME=${DB2_NAME}
      - DB_USER=${DB2_USER}
      - DB_PASSWORD=${DB2_PASSWORD}
      - DB_PORT=${DB2_PORT}
      - PGDUMP_URL=${DB2_PGDUMP_URL}
      - TZ=${TZ}
    env_file:
      - local.env
    ports:
      # exposing DB ports here for easier DB-access from localhost
      - "127.0.0.1:${DB2_PORT}:${DB2_PORT}"
    networks:
      - badapple_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${DB2_NAME} -p ${DB2_PORT}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./app
    depends_on:
      db:
        condition: service_healthy
      db2:
        condition: service_healthy
    environment:
      - APP_PORT=${APP_PORT}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB2_HOST=db2
      - DB2_NAME=${DB2_NAME}
      - DB2_USER=${DB2_USER}
      - DB2_PASSWORD=${DB2_PASSWORD}
      - DB2_PORT=${DB2_PORT}
    env_file:
      - local.env
    ports:
      - "127.0.0.1:${APP_PORT}:${APP_PORT}"
    networks:
      - badapple_network
    restart: unless-stopped

  ui:
    build:
      context: https://github.com/unmtransinfo/Badapple2-UI.git#main
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    env_file:
      - local.env
    ports:
      - "127.0.0.1:${UI_PORT}:8080"
    networks:
      - badapple_network
    command: npx vite --port 8080
    restart: unless-stopped
networks:
  badapple_network:
    driver: bridge

volumes:
  badapple_classic_data:
  badapple2_data:
